disabled_rules: # rule identifiers to exclude from running
  - colon
  - trailing_whitespace
  - vertical_whitespace
  - line_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - fastlane
  - firebase binaries
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
