# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'A2D2_iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  # Pods for A2D2_iOS

  target 'A2D2_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'A2D2_iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
